'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SCCommissions.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Friend ReadOnly Property Amount() As String
            Get
                Return ResourceManager.GetString("Amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BAND.
        '''</summary>
        Friend ReadOnly Property BAND() As String
            Get
                Return ResourceManager.GetString("BAND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There has been changes made, are you sure you want to exit before saving?.
        '''</summary>
        Friend ReadOnly Property ChangesMade() As String
            Get
                Return ResourceManager.GetString("ChangesMade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chemical.
        '''</summary>
        Friend ReadOnly Property Chemical() As String
            Get
                Return ResourceManager.GetString("Chemical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Count.
        '''</summary>
        Friend ReadOnly Property ClientCount() As String
            Get
                Return ResourceManager.GetString("ClientCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property Close() As String
            Get
                Return ResourceManager.GetString("Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COMMISSION.
        '''</summary>
        Friend ReadOnly Property COMMISSION() As String
            Get
                Return ResourceManager.GetString("COMMISSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property Exit_1() As String
            Get
                Return ResourceManager.GetString("Exit_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FROM.
        '''</summary>
        Friend ReadOnly Property FROM() As String
            Get
                Return ResourceManager.GetString("FROM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refer.
        '''</summary>
        Friend ReadOnly Property Refer() As String
            Get
                Return ResourceManager.GetString("Refer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retail.
        '''</summary>
        Friend ReadOnly Property Retail() As String
            Get
                Return ResourceManager.GetString("Retail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retal Type.
        '''</summary>
        Friend ReadOnly Property RetalType() As String
            Get
                Return ResourceManager.GetString("RetalType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved.
        '''</summary>
        Friend ReadOnly Property Saved() As String
            Get
                Return ResourceManager.GetString("Saved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select from the drop down list.
        '''</summary>
        Friend ReadOnly Property SelectDrop() As String
            Get
                Return ResourceManager.GetString("SelectDrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Error.
        '''</summary>
        Friend ReadOnly Property SelectError() As String
            Get
                Return ResourceManager.GetString("SelectError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Structure:.
        '''</summary>
        Friend ReadOnly Property SelectStructure() As String
            Get
                Return ResourceManager.GetString("SelectStructure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Type:.
        '''</summary>
        Friend ReadOnly Property SelectType() As String
            Get
                Return ResourceManager.GetString("SelectType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service.
        '''</summary>
        Friend ReadOnly Property Service() As String
            Get
                Return ResourceManager.GetString("Service", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to * &apos;Service&apos; is not applicable if Client Count is selected.
        '''</summary>
        Friend ReadOnly Property ServiceNotApplicable() As String
            Get
                Return ResourceManager.GetString("ServiceNotApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings Saved.
        '''</summary>
        Friend ReadOnly Property SettingsSaved() As String
            Get
                Return ResourceManager.GetString("SettingsSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Structure.
        '''</summary>
        Friend ReadOnly Property Structure_1() As String
            Get
                Return ResourceManager.GetString("Structure_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sundry.
        '''</summary>
        Friend ReadOnly Property Sundry() As String
            Get
                Return ResourceManager.GetString("Sundry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Error.
        '''</summary>
        Friend ReadOnly Property SystemError() As String
            Get
                Return ResourceManager.GetString("SystemError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TO.
        '''</summary>
        Friend ReadOnly Property TO_1() As String
            Get
                Return ResourceManager.GetString("TO_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Units Sold.
        '''</summary>
        Friend ReadOnly Property UnitsSold() As String
            Get
                Return ResourceManager.GetString("UnitsSold", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
